# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-07 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20171207_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('event', models.ManyToManyField(to='tracker.Event')),
            ],
        ),
        migrations.CreateModel(
            name='LabelValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.LabelTag')),
            ],
        ),
        migrations.RemoveField(
            model_name='label',
            name='event',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
