# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-07 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20171207_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeltag',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
