# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-14 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.Event'),
            preserve_default=False,
        ),
    ]
