# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-14 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_activity_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Status'),
        ),
    ]
