# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-16 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20171014_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.Status'),
            preserve_default=False,
        ),
    ]
