# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-19 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20171019_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='unique_identifier',
            field=models.CharField(max_length=500),
        ),
    ]
