# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20171019_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.Ticket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='parent_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.Team'),
            preserve_default=False,
        ),
    ]
