# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20171024_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='task_sub_type',
        ),
    ]
