# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-02 07:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_remove_event_task_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='agent',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
