# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-22 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_ticket_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='received',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
